# Generated by Django 5.0.1 on 2024-10-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos_created', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('average_watch_time', models.DurationField()),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('total_quiz_attempt_rate', models.FloatField(default=0.0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('average_watch_time', models.DurationField()),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_score', models.FloatField(default=0.0)),
                ('attempt_rate', models.FloatField(default=0.0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='analytics.video')),
            ],
        ),
    ]
