# Generated by Django 5.0.1 on 2024-10-12 11:42

import django.db.models.deletion
import uuid
import video_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=video_generator.models.upload_to_unique_filename)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=50)),
                ('script', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_length', models.IntegerField(default=60)),
                ('language', models.TextField(blank=True, null=True)),
                ('processing_mode', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('video_preview', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_length', models.IntegerField(default=60)),
                ('document_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_generator.documentprocessingjob')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('video_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_generator.videoprocessingjob')),
            ],
        ),
    ]
