# Generated by Django 5.0.1 on 2024-09-25 22:03

import video_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingjob',
            name='video_length',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='videoprocessingjob',
            name='video_length',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='file',
            field=models.FileField(upload_to=video_generator.models.upload_to_unique_filename),
        ),
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=50),
        ),
    ]
