# Generated by Django 5.0.1 on 2024-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingjob',
            name='processing_mode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
