# Generated by Django 5.0.1 on 2024-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0002_documentprocessingjob_video_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingjob',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
